/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;


/**
 *
 * @author evandro
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTextoBolha1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTextoBolha2 = new javax.swing.JLabel();
        lblFotoBolha = new javax.swing.JLabel();
        spnEscolha = new javax.swing.JSpinner();
        lblEscolha = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/Genie2pequeno.png"))); // NOI18N
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 163, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoBolha1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        lblTextoBolha1.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoBolha1.setText("Vou pensar em um numero entre 1 e 5. ");
        jPanel1.add(lblTextoBolha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 30));

        jLabel1.setFont(new java.awt.Font("Michroma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GÊNIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 242, 32));

        lblTextoBolha2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        lblTextoBolha2.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoBolha2.setText("Tente advinhar");
        jPanel1.add(lblTextoBolha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        lblFotoBolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balaoDeFalaPequeno.png"))); // NOI18N
        jPanel1.add(lblFotoBolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 320, 250));

        spnEscolha.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnEscolha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnEscolhaKeyTyped(evt);
            }
        });
        jPanel1.add(spnEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 30));

        lblEscolha.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        lblEscolha.setForeground(new java.awt.Color(255, 255, 255));
        lblEscolha.setText("Escolha: ");
        jPanel1.add(lblEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btnPalpite.setText("Palpite");
        btnPalpite.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 153)));
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        jPanel1.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 70, 30));

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);
        jPanel1.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        int numGenio = (int) (Math.random()*5) + 1;
        int palpite = (Integer) spnEscolha.getValue();
        if (numGenio == palpite){
            lblTextoBolha1.setText("");
            lblTextoBolha2.setText("   Acertou!!!");
        }else{
            lblTextoBolha1.setText("");
            lblTextoBolha2.setText("Errou!!! Pensei em: " + numGenio);
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void spnEscolhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnEscolhaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_spnEscolhaKeyTyped

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        lblTextoBolha1.setText("Vou pensar em um numero entre 1 e 5.");
        lblTextoBolha2.setText("Tente advinhar");
        spnEscolha.setValue(1);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFotoBolha;
    private javax.swing.JLabel lblTextoBolha1;
    private javax.swing.JLabel lblTextoBolha2;
    private javax.swing.JSpinner spnEscolha;
    // End of variables declaration//GEN-END:variables
}
